
site_name: Avant1's Notes
site_url: https://avantihub.github.io
site_author: Avant1
site_description: Avant1的笔记本
repo_url: https://github.com/Avantihub/avantihub.github.io
repo_name: Avantihub/note
copyright: Copyright &copy; 2024-2025 <a herf="https://github.com/Avantihub" target="_blank" rel="noopener">Avantihub</a>


theme:
  logo: assets/images/github0.png
  name: 'material'
  favicon: assets/images/github0.png
  custom_dir: overrides
  language: 'zh'
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle
    logo: material/notebook-outline
  palette:
    - scheme: default
      primary: White
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # 夜间模式
    - scheme: slate
      primary: White
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    
    - navigation.expand
    
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  

extra_css:
  - css/custom.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.18/dist/katex.min.css
#  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
#  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
#  - https://cdn.tonycrane.cc/utils/katex.min.css
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 5
  - admonition #应用admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite #添加了对内联代码块的语法突出显示的支持
  - pymdownx.snippets #使用简单语法将任意文件的内容嵌入到文档
  - pymdownx.superfences #允许代码和内容块任意嵌套，包括警告、选项卡、列表和所有其他元素

  - pymdownx.details #admonition可以折叠

  - attr_list 
  - md_in_html
  - pymdownx.keys #添加了一个简单的语法来允许呈现键盘按键和组合
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.critic 

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg 


  - pymdownx.tabbed:
      alternate_style: true

  # 允许使用任务清单即- []
  - pymdownx.tasklist:
      custom_checkbox: true

  # 允许渲染公式，还需要添加mathjax配置和JavaScript
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#arithmatex
  - pymdownx.arithmatex:
      generic: true

  - def_list #使用各类表格
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  - sane_lists
  - pymdownx.magiclink


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - rss
  - search
  - glightbox:
      width: 80%
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - writeups/AAA.md
  - changelog
  - statistics

nav:
  - Home:
      - index.md
  - Computer Science:
      - cs/index.md
      - 编程语言:
          - C/C++:
              - C语言: cs/pl/c_cpp/C/c.md
              - C09A: cs/pl/c_cpp/C/C09A.md
              - simu29: cs/pl/c_cpp/C/simu29.md
              - C++: cs/pl/c_cpp/CPP/cpp.md
              - Pointer: cs/pl/c_cpp/Pointer.md
          - Python:
              - Index: cs/pl/python/index.md
              - CS61A: cs/pl/python/cs61a.md
  - Assembly:
      - asm1: assembly/asm1.md
      - asm2: assembly/asm2.md
      - stk&Regi: assembly/stk.md
  - CodingProb:
      - P1010幂次方: codingprob/P1010.md
      - P1011车站: codingprob/P1011.md
      - P1098字符串展开: codingprob/P1098.md
      - Hello: codingprob/hello0.md
  - Life:
      - Optimistic: Life/optimistic.md
      - Memory Folding: Life/24lec0.md
  #- Math:
  #- Calculus: math/calculus/zjucalc24/quiz/anal_quiz2/index.html
