name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear GitHub Actions cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            ~/.npm
            ~/.pip
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Checkout repository
        uses: actions/checkout@v3 # 更新到最新版本

      - name: Set up Python
        uses: actions/setup-python@v4 # 更新到最新版本
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs-rss-plugin
          pip install mkdocs-glightbox
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-changelog-plugin
          pip install pymdown-extensions

      - name: Build MkDocs site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
